AddCSLuaFile'shared.lua'
AddCSLuaFile'cl_init.lua'
AddCSLuaFile'config.lua'
AddCSLuaFile'sh_/hooks.lua'
AddCSLuaFile'cl_/hooks.lua'
include'shared.lua'
include'sh_/hooks.lua'
include'sv_/hooks.lua'
